#!/usr/bin/env bash
if [[ -z $STOW_FOLDERS ]]; then
	STOW_FOLDERS="tmux,nvim,scripts,bash,i3,polybar,hypr,waybar,kitty,xbindkeys,xmodmap,hotkeys,starship,fish"
fi

if [[ -z $DOTFILES ]]; then
	DOTFILES="${HOME}/.dotfiles"
fi

STOW_FOLDERS=${STOW_FOLDERS} DOTFILES=${DOTFILES} $DOTFILES/install
