require("mason-lspconfig").setup({
    ensure_installed = { 
      "clangd",
      "lua_ls", 
      "rust_analyzer",
      "cssls",
      "gopls",
      "grammarly",
      "graphql",
      "html",
      "jsonls",
      "tsserver",
      "pyright",
      "ruby_lsp",
      "terraformls",
      "vuels",
      "cmake",
      "ansiblels",
      "bashls"
    },
})
