#!/usr/bin/env bash

# Define the base directory for all projects
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo $SCRIPT_DIR
source "$SCRIPT_DIR/workspace"

selected=$(get_work_directories)

# If nothing was selected (e.g., fzf was cancelled), exit
if [[ -z $selected ]]; then
    echo "No project selected. Exiting."
    exit 0
fi

pushd "$selected_name"
