#!/usr/bin/env bash

# Define the base directory for all projects
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/workspace"

selected=$(get_work_directories)

# If nothing was selected (e.g., fzf was cancelled), exit
if [[ -z $selected ]]; then
    echo "No directory selected. Exiting."
    exit 0
fi

# Change current tmux pane directory
printf "cd '%s'\nclear\n" "$selected" | tmux load-buffer - &&
tmux paste-buffer -t !